language: node_js

node_js:
  - "0.10"
  
services:
  - redis-server
  - mongodb
  - rabbitmq


before_script:
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart
  - sudo rabbitmqctl status
  - sudo rabbitmq-plugins list
  - npm install joola.io
  
script: 'make test-cov'
after_success: 'make coveralls'

notifications:
  email:
    - 'updates@joo.la'
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c4aa904abf1dabb42f95
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false