language: node_js

node_js:
  - "0.10"

addons:
  sauce_connect: 
    username: joola-io
    access_key: 8ac80e3d-093f-4292-aa48-95f5656b0785 
  
before_script:
  - npm install -g grunt-cli

script: 'grunt test'
after_success: 'grunt sauce'

notifications:
  email:
    - 'updates@joo.la'
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a43ba3884562555a9c1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false