language: node_js

node_js:
  - "0.10"

addons:
  sauce_connect: 
    username: joola
    access_key: 
      secure: "LNThabrSexSJ2aC9rXghzBBUxVT4GLqmOp3ss+x3Y5nZWqVhDk84uzVycC0tAbdJUgdYGtHtusYBRaJHaqZKpFLqWNsnL0xynWrctc0Hv/9xJGfo4vKjdIPlDkQ9iyIdw9/63sjIbkKy+KHqT5yyoLgy7meUFkPzzcKiNb3ySn4="
  
before_script:
  - npm install -g grunt-cli

script: 'grunt test:sauce'
#after_success: 'make coveralls'

notifications:
  email:
    - 'updates@joo.la'
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c4aa904abf1dabb42f95
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false