language: node_js

node_js:
  - "0.10"

env:
  global:
    - secure: 'jnPXvigS2cHUv7hQRM/K1tuGvpOabVU+8ziB9kdC5vsm7Q30drnomNW0dMT3nxj8CdS/H49l3XBmRMXFYrB8+XA2Fa99CsIGwCg8QKFI7H7znwPV71l0JlCWOXQ6rweJMEQfusqDIXJ4EoD/u+Dq2yYFFSygF9V9uDn9yAeZIXQ='
    - secure: 'XUt6SSn4WbbQFw7IpYVpfhX1AeRjsGnsRkUqyqtkwFg8ABh8KWxQy/yZ6A6vxLe3in1f/AS9InVGBCnb4F9D64HDuQ1nhNRtUaBaaJquk5uIV7Rt2ecHEnyvmDsjUOjqfbYCjHLL3kOFIE680F49p4cJE5G6aUbO+FQoVHzMBn4='

addons:
  sauce_connect: 
    username:
      secure: 'jnPXvigS2cHUv7hQRM/K1tuGvpOabVU+8ziB9kdC5vsm7Q30drnomNW0dMT3nxj8CdS/H49l3XBmRMXFYrB8+XA2Fa99CsIGwCg8QKFI7H7znwPV71l0JlCWOXQ6rweJMEQfusqDIXJ4EoD/u+Dq2yYFFSygF9V9uDn9yAeZIXQ='
    access_key:
      secure: 'XUt6SSn4WbbQFw7IpYVpfhX1AeRjsGnsRkUqyqtkwFg8ABh8KWxQy/yZ6A6vxLe3in1f/AS9InVGBCnb4F9D64HDuQ1nhNRtUaBaaJquk5uIV7Rt2ecHEnyvmDsjUOjqfbYCjHLL3kOFIE680F49p4cJE5G6aUbO+FQoVHzMBn4='
  
before_script:
  - npm install -g grunt-cli

script: 'grunt test:sauce'
#after_success: 'make coveralls'

notifications:
  email:
    - 'updates@joo.la'
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c4aa904abf1dabb42f95
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false